# Generated by Django 6.0.5 on 2026-05-22 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_customer', models.CharField(max_length=100)),
                ('gst_number', models.CharField(blank=True, max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(blank=True, max_length=8, unique=True)),
                ('date', models.DateField()),
                ('duedate', models.DateField(blank=True, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('EXTRUSION', 'Aluminium Extrusion(sq.ft)'), ('PROFILE', 'Aluminium Profile(kg)'), ('SHEET', 'Aluminium Sheet(Nos)'), ('ROD', 'Round Aluminium Rod(kg)')], max_length=100)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField()),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('anodising_type', models.CharField(choices=[('COLOUR', '50-70'), ('HARD', '80-120'), ('NATURAL', '70-180'), ('TYPE_II', '100-150'), ('TYPE_III', '75-150')], max_length=100)),
                ('thickness', models.CharField(choices=[('5-10', '5-10µ'), ('15-25', '15-25µ'), ('25-50', '25-50µ'), ('50+', '50µ')], max_length=20)),
                ('color_finish', models.CharField(choices=[('BLACK', '5-8'), ('BRONZE', '6-8'), ('CLEAR', '0'), ('GOLD', '8-10'), ('SILVER', '12-15')], max_length=100)),
                ('process_charges', models.CharField(choices=[('DEGREASING', '3-5'), ('ETCHING', '5-8'), ('POLISHING', '8-10'), ('SEALING', '2-4'), ('TEFLON COATING', '10-15')], max_length=20)),
                ('base_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thickness_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('process_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='system.jobnumber')),
            ],
        ),
    ]
