# Generated by Django 6.0.5 on 2026-05-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_jobnumber_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
